const mongoose = require("mongoose");

const saleSchema = new mongoose.Schema({
    billNo:Number,
    lot:Number,
    startDate: Date,
    billDate:Date,
    village:String,
    customerName:String,
    mobileNo:String,
    MB:Number,
    JF:Number,
    PDR:Number,
    HF:Number,
    HFX:Number,
    JB:Number,
    JBX:Number,
    KH:Number,
    RK:Number,
    GIR:Number,
    SH:Number,
    DN:Number,
    SHEATH:Number,
    GLOVES:Number,
    goat:Number,
    goatAmount:Number,
    totalGoat:Number,
    sorted:Number,
    sortedAmount:Number,
    totalsorted:Number,
    totalPackageDose:Number,
    packageAmount:Number,
    extraFSD:Number,
    FSDAmount:Number,
    totalFSD:Number,
    extraAIGloves:Number,
    AIGlovesAmount:Number,
    totalAIGloves:Number,
    extraAISheeth:Number,
    AISheethAmount:Number,
    totalAISheeth:Number,
    LN2:Number,
    LN2Amount:Number,
    TotalLN2Amount:Number,
    extraAmount:Number,
    total:Number,
    gstPer:Number,
    gstAmount:Number,
    finalTotal:Number
});

const Sale=mongoose.model('sales',saleSchema);
module.exports=Sale;